### ISSUE TITLE
Only works after wake

### ISSUE THREAD

**Issue by tianenchong** [chris1111/VoodooHDA-2.9.0-Clover-V10#1]
The audio works for a few seconds after boot and then it stops. I discovered that it only works perfectly when I put my Mac to sleep and wake it up again. Thank you for your support and hardwork.
[codec_dump.txt](https://github.com/chris1111/VoodooHDA-2.9.0-Clover-V10/files/1150354/codec_dump.txt)

**Comment by chris1111** [comment]
For any question about VoodooHDA you must post on the thread of the Developer
http://www.insanelymac.com/forum/topic/314406-voodoohda-290/

**Comment by tianenchong** [comment]
Okay. Thank you.
